<?php
?>
<h2>Blog Article Form</h2>
<p>The <i>Blog Article</i> Form allows you to create a new blog article or edit an 
existing article. Using the HTML editor, you can enter the article content with 
HTML formatting. The article teaser is meant to provide your audience with just 
enough information to spark their interest in reading the article. It should be 
only about one or two sentences. The article type provides a mechanism for 
segmenting articles within your site so that certain types are displayed in 
groups or in different pages or modules.</p>