<?php
?>
<h2>Blogs</h2>
<p>This page displays the blogs that have been written for the web site. 
To edit a blog, click on its title. The publication status is shown in the last column. 
A green checkmark icon signifies that the blog is published; a red cross icon signifies the article is not published. 
Click the icon to change the status. To create a new blog, click the <i>Add a Blog</i> button at the bottom of the page.</p>

<p>The component page with identifier <i>blogs</i> displays all the 
published articles. If you wish to display only certain blogs, you will need to 
have a developer create a component page or a code module.</p>

