<?php
?>
<h2>Blog Subscriber Form</h2>
<p>The <i>Blog Susbriber</i> Form  allows users to select a Blog of interest to subscribe 
and enter an email address to sign up to receive an email every time a new blog post is 
published. The email notification message itself is customizable via the email templates 
feature, and the email can (and should always) contain an unsubscribe link allowing the user 
to unsubscribe at any time.</p>