<?php
?>
<h2>Calendar Details</h2>
<p>The <i>Calendar Form</i> allows you to create a new calendar or edit an existing calendar. 
You can define the user roles who should have access to Read Access (ability to view events) and
Write Access (permission to add/updates events). If your web site has a set of defined <a href='/admin/event_types'>event types</a>,
you can identify which types are applicable to the calendar you are adding or updating.</p>