<?php
?>
<h2>Calendars</h2>
<p>The <i>Calendars</i> page displays the calendars created for the web site.
The Calendar feature allows you to segment scheduled events and activities among various
user groups. For example, an organization may wish to display private internal events on 
one calendar and public events on another. To edit a calendar, click on its title. To create a new calendar, click the 
<i>Add a new Calendar</i> button at the bottom of the page.</p>