<?php
?>
<h2>Calendar Event Form</h2>
<p>The Calendar <i>Event Form</i> allows you to add or edit calendar events. The <i>Event Type</i> drop down
shows either all unique event types for saved events or the <a href='/admin/event_types'>Event Types</a> defined in CMS.
When the event description is complete, you can click the <i>Published</i> checkbox to display the event on the selected calendar.</p>