<?php
?>
<h2>Event Types</h2>
<p>The <i>Event Types</i> list page displays any event types you have defined for your 
web site's <a href='/admin/calendars'>calendars</a>. Defining a sets of event types allows
you to constrain the available set of choices in the event type drop down to a set that
you believe is applicable to your organization. If you choose not to define a sest of 
event types, the system will allow users to select from the set of event types
already saved in the database or enter a new one.</p>