<?php
$help_map = array(
				"title"		=>	"Calendar",
				"pages"		=>	array(
					"calendar_events"			=>	"Calendar Events",
					"calendar_form"				=>	"Calendar Details",
					"calendar_view"				=>	"Calendar Month Display",
					"Event Form"				=>	"Event Form",
					"Event Type Form"			=>	"Event Type Form",
					"Event Types"				=>	"Event Types",
					"Events"					=>	"Events",
					)
				);

?>