<?php
?>
<h2>Email Templates</h2>
<p> <i>Email templates</i> are customizable email messages that your web site uses to 
send notification messages. 
This page displays the list  of  email templates that have been written for your site. 
To edit an email template, click on its name. To create a new email template, click the <i>Add a Template</i> 
button at the bottom of the page.</p>



