<h2>Activity Report</h2>

<p>The Activity Report can be accessed from the <b>User Management</b> administration section,
and can be filtered by authenticated and unauthenticated users (even unauthenticated users
are provided a session ID, so we can track their paths through the system individually).</p>
<p>By clicking on a Session ID from the list you are taken to a report of the activity 
under that session, showing the user's detailed click-track.</p>

<p>For more information see <a href='page?src=activity_tracker&page=index'>Activity Tracking and Feedback</a>.</p>