<h2>Session Details</h2>
<p>The Session Details page lists in chronological order all the requests made to the
server by a user in the given session. This provides details of the path the user has
taken through the application. By default image and other resource requests are excluded
from this list, but they can be shown by clicking on the checkbox at the top of the page.</p>

<p>For more information see <a href='page?src=activity_tracker&page=index'>Activity Tracking and Feedback</a>.</p>