<?php
?>
<p>This page displays the articles that have been written for the web site. 
To edit an article, click on its title. The publication status is shown in the last column. A green checkmark icon signifies
that the article is published; a red cross icon signifies the article is not published. 
Click the icon to change the status. To create a new article, click the <i>Add an Article</i> button at the bottom of the page.</p>

<p>To display the articles to the public or to specific types of site users, you will need to have a developer create a component page or a code module. 
You can create a component page that displays articles of a specific type or only the most recent articles. You may wish to have certain articles display 
to registered site users and others displayed to site visitors.</p>
