<?php
?>
<h2>Articles</h2>
<p>This page displays the articles that have been written for the web site. 
To edit an article, click on its title. The publication status is shown in the last column. A green checkmark icon signifies
that the article is published; a red cross icon signifies the article is not published. 
Click the icon to change the status. To create a new article, click the <i>Add an Article</i> button at the bottom of the page.</p>

<p>The component page with identifier <i>articles</i> displays all the 
published articles. If you wish to display only certain articles or article 
types, or to differentiate articles displayed to different user roles or site 
visitors, you will need to have a developer create a component page or a code module.</p>
