<h2>Component Pages</h2>
<p>Components can provide dynamic pages for your Fakoli web application.
This page lists each component page by component and allows you to enable
or disable component pages by clicking on the tick or cross in the <b>Enabled</b>
column.</p>
<p>Please note that even in a component page is enabled, it will not be accessible
to your users until it is assigned as a content page to one or more <a href='page?src=section&page='>Sections</a>.
Likewise, if a page is assigned to a section but is not enabled here it will also
not be available. This feature allows you to disable component pages if you run
into a problem without having to change their section mappings.</p>