<h2>The Component List</h2>
<p>The Component List page displays the list of currently enabled components
that make up your Fakoli application. Each component lists its name, author,
version and a brief description of what it does. You can click on the component
name to get a more detailed description based upon the component's manifest.</p>

<p>At the bottom of the page you will see a button labeled <b>Scan for Component Updates</b>.
Clicking on this button will tell Fakoli to rescan all the component directories, compare
the versions of the components in those directories with the current version in the component
list, and if necessary run any updates to bring those components up-to-date. This process will
also detect any new component or admin pages that have been added to components since the
last scan.</p>

<p>It is important to rescan the components whenever you make any code changes that
require an update to the database schema, or which add or remove component or admin pages.
For more information on the inner workings of Fakoli's component manager, go to the page 
<a href="page?src=component&page=index">How Fakoli Manages Components</a></p>