<?php
$help_map = array(
				"default"	=>	"index",
				"title"		=>	"Component Management",
				"pages"		=>	array(
					"index"						=>	"How Fakoli Manages Components",
					"components"				=>	"The Component List",
					"component_pages"			=>	"Component Pages",
					"component_page_form"		=>	"The Component Page Form",
					"component_page_modules"	=>	"Mapping Component Page Modules"));
?>