<?php
?>
<h2>Menu Form</h2>
<p>The <i>Menu</i> Form allows you to create a new menu or edit an existing menu. 
Select a Site from the dropdown list. Type a name that you would like it to be called. 
The name can contain spaces. Enter the unique identifier for this menu,  identifiers should consist 
only of the characters a-z, 0-9 and underscore(no spaces, punctuation, etc. ). Description Field is used to 
briefly describe the menu you are defining. Css Class is an optional field, enter the class name if you have one.
Click on Add/Update Menu to save.
</p>