<?php
?>
<h2>Menu Item Form</h2>
<p>The <i>Menu Item</i> Form allows you to create a new menu item or edit an existing menu item. 
Title is given to the menu item in the 'Title' field. 'Link' field is used to add a hyper link to the menu item. This menu item can also be linked to any page/component page etc; within the site.
The <i>Browse</i> button can help you link to it.
Choose a Role/Roles as to who can see this menu item. Click 'Publish' if you want it available for use within your site.
</p>