<?php
?>
<h2>Menu Items</h2>
<p>This page displays the menu items or sub menus defined for a menu in a tree structure. The tree structure here
can be expanded or collapsed which makes it easier to differentiate between menus, sub menus and/or sub-sub menus.
Each menu items can again contain a hierarchy of sub menu items. 
To edit or update any menu item click on it within the tree structure. To create a new menu item, click the 
<i>Add a New Menu Item</i> button at the bottom of the page.</p>
