<h2>List of Scheduled Tasks</h2>
<p>This page displays the list of scheduled tasks provided by the components deployed on your site.
Active tasks are shown with a green checkmark, inactive tasks are shown with a 
Click on the<b>Task Name</b> to configure the schedule or examine the execution logs for a given tasks.
The <b>Last Run</b> column shows the date and time that each task was last executed. The <b>Status</b> 
column shows the status returned from that last run.
</p>