<h2>The Schedule Task Form</h2>
<p>This form allows you to configure when your scheduled task will be run.</p>
<p>If you want the task to run every hour, check the <b>Run every hour</b> checkbox (this will override any explicity schedule). 
To run the task on specific times or days, click on the corresponding points in the task schedule grid. Finally, you can
enable or disable the task via the <b>Active</b> checkbox.</p>
